### ISSUE TITLE
Need example using bioboxes

### ISSUE THREAD

**Issue by jfroula** [bioboxes/rfc#121]
I am trying to build an image for a metagenomic assembler for CAMI. CAMI has supplied a template image they would like for me to use ("docker pull cami/assembly").   I also  see from their website that I'm suppose to use bioboxes ("https://data.cami-challenge.org/").  

I'm assuming that I should build an image that starts off with "FROM cami/assembly" and then run the example code  that is supplied in the "How to Create a Biobox" section ("http://bioboxes.org/validate-biobox-file/") to run the validation, and the final line of this Dockerfile would be something to run the assembler like "ENTRYPOINT ["assemble"]".

Please let me know if I'm on the right track and offer any examples if you have any.  
Thanks

Jeff Froula
JGI
2800 Mitchell Dr.
Walnut Creek, Ca.
94598

**Comment by pbelmann** [comment]
Hi,
the base images provided by CAMI are based on the biobox assembler version ([0.8.0](https://github.com/bioboxes/rfc/blob/1aaeffc1f97dbea1ec05016a4a45e739dd47e20e/container/short-read-assembler.mkd)). The bioboxes [getting started](http://bioboxes.org/getting-started/), [how to create a biobox](http://bioboxes.org/how-to-create-a-biobox/) pages and the [validator](http://bioboxes.org/validator/short-read-assembler/) are based on the new bioboxes [0.9.0](https://github.com/bioboxes/rfc/blob/master/container/short-read-assembler/rfc.mkd) version. This version is new since last week and I suggest that you try out the newer version with the [getting started page](http://bioboxes.org/how-to-create-a-biobox/) and our examples (e.g: [velvet](https://github.com/bioboxes/velvet) or [minia](https://github.com/bioboxes/minia)). Sorry for the confusion.

**Comment by michaelbarton** [comment]
@jfroula sits next to me at the JGI. He's making an assembler for CAMI
challenge and trying to create a biobox. I asked him to post any issues he has
on the issue tracker as this might help us identify any problems in the
documentation. I would like to work on the documentation so that it is as
simple as possible to create a biobox, this will allow many people to create
bioboxes of their software, or at least assemblers to begin with.

I've update the getting started guide, and there is at least a user guide for
bioboxes - http://bioboxes.org/guide/user/.

A more fleshed-out developer guide would be a good next step too.

**Comment by michaelbarton** [comment]
We have added additional resources includeing [a developer guide][dg] and [a
user guide][ug]. @jfroula please open another if you believe there are futher
areas that the website could be improved to help you with creating a biobox.

[dg]: http://bioboxes.org/guide/developer/
[ug]: http://bioboxes.org/guide/user/
