### ISSUE TITLE
bioboxes.org bootstrap

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/rfc#150]
We are using the bootstrap css framework on bioboxes.org.
At the moment we are downloading the library package with an external script and referencing the package in our website.
Furthermore the .js  file is included by using a cdn.
I think we can skip the step of downloading the package and avoid the usage of a cdn by using a ruby/gem/middleman mechanism.
There is a bootstrap-sass gem and sprockets library that allows the download and usage of the bootstrap css framework in middleman.

**Comment by michaelbarton** [comment]
If I remember, the bootstrap is downloaded because the source is required to
use the mixins in other parts of the less stylesheets. We could use sass plugin
though I believe we would have to convert the existing stylesheets to sass.

The .js cdn could be swapped by including the bootstrap css in the javascripts
directory and including it in `all.js`.

**Comment by michaelbarton** [comment]
I will close this issue as inactive
