### ISSUE TITLE
Write an first draft abstract for bioboxes for BOSC 2015

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#65]
Bioboxes should create a presentation for BOSC 2015. A first step is to read
the guidelines for abstract submission for BOSC 2015 and write then write first
draft. This should be shared with with the members of the core team.

**Comment by avilella** [comment]
Abstract call to open March 5th:

http://www.open-bio.org/wiki/BOSC_Abstract_Submission

**Comment by michaelbarton** [comment]
Discussed at meeting #67. This is not a immediate priority, however this will
be a priority at the next biweekly meeting as the abstract deadline is April 3.

**Comment by michaelbarton** [comment]
I've created a github repository for maintaining the abstracts - https://github.com/bioboxes/abstracts. When writing the BOSC abstract please create a pull request to this repository.

**Comment by michaelbarton** [comment]
@avilella Would you mind writing a draft of the abstract? It would be good to have a first version before the next biweekly meeting.

**Comment by avilella** [comment]
First very rough draft.

**Comment by michaelbarton** [comment]
Thanks for doing this @avilella. I've added my own revisions to your repository
in avilella/abstracts/#1. The are some [abstract requirements for
BOSC2015][req]. One of them is the list of authors, I put "bioboxes community".
I'm not sure if this will be acceptable though.

[req]: http://www.open-bio.org/wiki/BOSC_Abstract_Submission

**Comment by avilella** [comment]
Ok, I will stick to markdown ATM since they have a Markdown to PDF way of
conversion on the website:
https://s3.amazonaws.com/chapmanb/openbio/bosc_template_pandoc.tar.gz

Can people give me their affiliation details below as you would do for a
pubmed article please?

Full author name (as used in pubmed)
Organization name
Location

@michaelbarton
@abremges
@fungs
@avilella
@leprevost
@ypriverol
@pbelmann

Who wants to be first and who wants to be last? I've looked at the work
done so far, and tentatively put @michaelbarton first as he will probably
be the one presenting, and @pbelmann last as he's been the one doing a lot
of work so far.

Cheers,

A.

**Comment by abremges** [comment]
I looked up most affiliations etc. for my pull request here: https://github.com/bioboxes/commentary-article/pull/1

I'd propose joint first authorship for @michaelbarton and @pbelmann instead.
At least some of our PIs should be included, providing funding and guidance behind the scenes.
E.g. @asczyrba is actively involved, regularly discussing issues with @pbelmann and me.

**Comment by avilella** [comment]
Thanks.

Adding @asczyrba as well.

@abremges, can you list the PI info below so that we have the complete list
of authors ready?

**Comment by abremges** [comment]
Sure, I had the info ready anyway. My best guess, sorted alphabetically.
Everyone should double-check, especially @leprevost and you, @avilella:


GitHub | Name | Affiliation | Role
---|---|---|---
@michaelbarton | Michael Barton | DOE Joint Genome Institute, 2800 Mitchell Drive, Walnut Creek, CA 94598, USA. |
@pbelmann | Peter Belmann | Faculty of Technology and Center for Biotechnology, Bielefeld University, Universitätsstraße 25, 33615 Bielefeld, Germany. |
@abremges | Andreas Bremges | Faculty of Technology and Center for Biotechnology, Bielefeld University, Universitätsstraße 25, 33615 Bielefeld, Germany. <br/>&<br/> Helmholtz Centre for Infection Research, Inhoffenstraße 7, 38124 Braunschweig, Germany. |
@fungs | Johannes Dröge | Helmholtz Centre for Infection Research, Inhoffenstraße 7, 38124 Braunschweig, Germany. |
@leprevost | Felipe Leprevost | Fiocruz, Carlos Chagas Institute, Rua Prof. Algacyr Munhoz Mader, 3775, CIC 81350-010 Curitiba/PR, Brasil. |
@ypriverol | Yasset Perez-Riverol | European Molecular Biology Laboratory, European Bioinformatics Institute (EMBL-EBI), Wellcome Trust Genome Campus, Hinxton, Cambridge, CB10 1SD, United Kingdom. |
@avilella | Albert Vilella | Onto.it Holdings Ltd., 62-66 Victoria Road, Cambridge, CB4 3DU, United Kingdom. |
@accopeland | Alex Copeland | DOE Joint Genome Institute, 2800 Mitchell Drive, Walnut Creek, CA 94598, USA. | PI
@alicemchardy | Alice McHardy | Helmholtz Centre for Infection Research, Inhoffenstraße 7, 38124 Braunschweig, Germany. | PI
@asczyrba | Alexander Sczyrba | Faculty of Technology and Center for Biotechnology, Bielefeld University, Universitätsstraße 25, 33615 Bielefeld, Germany. | PI

**Comment by avilella** [comment]
Thanks, I think I added it as you have it in the abstract mkd file now.

**Comment by ypriverol** [comment]
@michaelbarton @avilella I don't know if is possible to put Henning Hermjakob My PI also. It will help in the future and also it has been involve in the development of standards like MIAPE MIAME, etc. But just if I finally contribute a lot.

**Comment by abremges** [comment]
I think each of us should discuss this with his PI at some point in the future, and keep the [ICMJE authorship criteria](http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html) in mind. Given the origin of bioboxes (it started as a collaboration between Michael's [nucleotid.es](http://nucleotid.es/) and our [CAMI challenge](https://data.cami-challenge.org/)), some PIs are somewhat pre-selected.

But I don't mind including each and every PI, almost doubling the list of authors, if (s)he supported the effort we put in bioboxes. It's another story if you had to invest a big chunk of your free time in bioboxes because you care and they didn't. Let's discuss this briefly in our next call.

**Comment by ypriverol** [comment]
@abremges Agree!!

**Comment by pbelmann** [comment]
abstract submitted see https://github.com/bioboxes/abstracts/pull/2
