### ISSUE TITLE
The databases section in the bioboxes RFC should be clarified.

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/rfc#69]
This section of the RFC is ambiguous. For example some containers do not need
to use any databases. Also the file `databases_structure.txt` is very large and
is role in the RFC is unclear.

A patch for this may move this section to the relevent RFCs or provide further
text as to how this is used.

**Comment by michaelbarton** [comment]
@pbelmann could you comment on this issue please?

**Comment by pbelmann** [comment]
The database section is a temporary solution to the problem that you simply can not delimit the databases a binning or profiling tool could use. Binning or profiling tools could use any kind of information, thus any kind of database. But I'm happy if someone could come up with a better solution.

The database section is linked in profiling and binning tools spec.

**Comment by fungs** [comment]
We should probably stay completely away from what a DB folder (I would rather call it custom data or similar) should contain and leave it to the container types or implementors what extra data they might need to pass. Each input folder by default should have a distinct type but later, when we use proper signatures, subfolders can provide different types.

I would try to standardize name spaces alias subfolders for common data which is too complex to pass as elementary instances. IMO, we should also provide guidance to what type of data should be considered a "database" (I would really try to avoid this term as it means something completely different for IT or data storage systems) and when proper file types should be preferred.

**Comment by michaelbarton** [comment]
Discussed in meeting #67. We could not reach an immediate consensus on how to
fit this large file into the existing RFCs. @fungs will propose possible
solution.

**Comment by pbelmann** [comment]
> We should probably stay completely away from what a DB folder (I would rather call it custom data or similar) should contain and leave it to the container types or implementors what extra data they might need to pass. Each input folder by default should have a distinct type but later, when we use proper signatures, subfolders can provide different types.

@fungs 
As a solution for this issue I would say that we remove the [database structure file](https://github.com/bioboxes/rfc/blob/master/databases_structure.txt) and just define types like: refseq, COG, NCBI Genomes, taxonomy and BLAST DBs. Each type will be available as a yaml type:

```YAML
- value: STRING
  type: STRING
```

where

 * value is the path to the database
 * type can be refseq, blastdb, cog, ncbi_genomes and taxonomy 
    
One reason for defining the database structure file was that we ensure that a tool always works with the provided databases. But I think it should be enough to just provide a link to the ncbi ftp site.

Furthermore we need something like a cache property. We need this because for example the binning tool [kraken](https://github.com/pbelmann/kraken) builds its own database and one step of the default task is at the moment to download the miniKraken database (2.7 GB). When we have a cache directory that is mounted writeable to the container, we could just reuse the database on a second run.

**Comment by pbelmann** [comment]
As discussed in our biweekly meeting (see [summary](https://github.com/bioboxes/rfc/issues/122)) I have splitted the database structure file in 5 parts and added them in my fork of [bioboxes](https://github.com/pbelmann/rfc/blob/feature/new_binning_spec/container/binning/binning.mkd#databases-definition). Each part has its own tag (refseq, blastdb,...) and can be specified in the yaml. As discussed in the meeting, this is not the best solution and must be improved in higher versions of bioboxes.
Furthermore I added the [cache property](https://github.com/pbelmann/rfc/blob/feature/new_binning_spec/container/binning/binning.mkd#cache-definition).

Both definitions will be available with the binning spec 0.9.0 .
