### ISSUE TITLE
Formal acceptance of Docker Compose (the artist previously known as Fig)

### ISSUE THREAD

**Issue by leipzig** [bioboxes/rfc#71]
I want to suggest the group address the issue that many Bioboxes themselves will have dependence on other common containers. In many workflows you will want to preserve the segregation of tasks, so that if two applications both require BLAST they can both simply link to the shared BLAST container.

Docker Compose is designed to orchestrate these dependencies so it might play a role in Bioboxes.

**Comment by avilella** [comment]
I agree. Fig is picking up a lot of momentum, so it's going to be solving
many of the problems we are thinking about in the short and mid term
future.

**Comment by michaelbarton** [comment]
Thank you for the suggestion @leipzig. I have been looking at Docker compose
and fig. I believe this tool is used for creating long running services, such
as starting a web service container and database container at the same time. I
think the workflow manager bioboxes would require is way to specify and start
one container, pass data to it, then pass the resulting output to another
container and so forth.

One think we have discussed is type signatures for containers (#9). This way
you automatically pass data between then because the interfaces are clearly
defined.

**Comment by michaelbarton** [comment]
Unless there are further comments, I will close this issue.
