### ISSUE TITLE
open communication and collaboration between bioboxes and common-workflow-language CWL

### ISSUE THREAD

**Issue by avilella** [bioboxes/rfc#79]
Hi,

I attended the common-language-framework conference call together with Nebojsa Tijanic (NT), Michael Crusoe (MC), Peter Amstutz (PA), Maxim Mikheev (MM), and John Kern (JK).

John Kern, @kern3020 , currently collaborating with bcbio, mentioned that it would be good to catch up so that he can tell us the way they have been using docker to put complex bioinformatics apps inside containers.

Just writing a pointer here for @kern3020 so he can say 'Hi'.

@michaelbarton , does he need auth to comment on this issue?

**Comment by michaelbarton** [comment]
The issues are open to comments from anyone. I would be interested in hearing
more about this. Perhaps @kern3020, @mr-c, or both might like to attend the
second half of our next meeting (#67) to discuss this with us.

**Comment by pbelmann** [comment]
It would be nice if anyone from the common-language-framework team could attend our meeting since like @avilella  stated in #61 that we have similar solutions for similar challenges.

**Comment by mr-c** [comment]
Thank you @michaelbarton for the invitation. I'm just a bioinformatics tool developer, not a workflow platform dev. I'm happy to talk about other aspects of CWL.

**Comment by kern3020** [comment]
Hello, 

Like Michael Crusoe, I am interested in cwl from a point of view of bringing my pipeline to it. Platform builders (e.g., biodatomics, seven bridges, curoverse) are really the authority on cwl proper. 

When I heard Albert's description of bioboxes, it seemed to have some similarities to bcbio ( https://github.com/chapmanb/bcbio-nextgen).  Brad Chapman is our leader and the project has been around for a few years. It focuses on secondary analysis for NGS data. 

With all the tools and data sets, the installation is complex. Last year, the bcbio pipeline was encapsulated via docker. This was a big help. 

When I spoke with Albert briefly in the CWL status meeting, I thought we could share notes as we progress through our respective projects.  Since then I began working with a cool little startup called AccuraGen ( http://www.accuragen.com/ ). Should be an exciting ride!  The downside is my time is now quite limited. I will not be able to continue my port of bcbio to cwl at this time. 

Regards,
John

**Comment by avilella** [comment]
Notes from @tetron explanation of CWL:

- CWL: describe scientific workflows

- portability, many platforms, very difficult to port workflows due to
  external configurations

- tool wrapper, data model

- dependencies are really challenging, a lot of configuration
  involved, docker is a wonderful solution

- what is missing is a uniform way describe the input and command line
  to invoke the container, output of the tool that goes into your
  storage system or pipes into next tool

- tool description language - describes input signature function
  programming language, files, strings, integers

- describes how to translate into cmd, docker container cmd that is
  built, with data files mounted into the container, tool gets the
  output of the container, output schema to find the output files

- second part is defining a workflow, combine a number of these tools
  together, outputs

- as few requirements on the docker container as possible, not like
  BaseSpace

- Peter is developer on the arvados, works for curoverse

- experience is that is great to have all tools inside docker
  containers, but additional provisioning of the docker container that
  has to happen: python inside the container but the container hasn't
  got

- CWL not focus on building containers

- arvados we are an emerging platform, we are interested in building
  standards, bring people on to our open source platform

- status, have people attending both meetings, more complementary, CWL
  underlying technology

- how to invoke a container, parameters, ins and outs

- we have running code, specification, describing the behaviour of the
  reference implementation that has been written, expanding pilots
  beyond toy examples

- implementation wins, documentation is necessary

- success is a well-specified implementation, have a specification
  that is grounded in a practical approach based on everybody's experience

- different vendors understand the specification

- agreed that we are going to keep attending each others conf calls
  and show each others specs as they stand now

**Comment by michaelbarton** [comment]
This discussion in this ticket has trailed off. I will close, and we can open more specific discussion tickets as necessary.
